extensions:
  memory_ballast:
    size_mib: 512
  zpages:
    endpoint: 0.0.0.0:55680

receivers:
  otlp:
    protocols:
      grpc: 
        endpoint: "localhost:5137"

processors:
  batch:
    send_batch_size: 1000
    timeout: 10s

exporters:
  logging:
    logLevel: debug
  otlphttp:
    endpoint: "http://localhost:4318"

service:
  telemetry:
    logs:
      level: "DEBUG"
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, logging]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, logging]

  extensions: [memory_ballast, zpages]
