extensions:
  memory_ballast:
    size_mib: 512
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:
    send_batch_size: 1000
    timeout: 10s

exporters:
  logging:
    logLevel: debug
  otlphttp:

service:

  pipelines:

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, logging]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, logging]

  extensions: [memory_ballast, zpages]
